import { Validators } from '@angular/forms';
import { Otpbox } from '../input_type/otpbox';

export const VERIFICATION_OTP_FIELDS = [
  new Otpbox({
    value: '',
    key: 'digit1',
    required: true,
    order: 1,
    type: 'text',
    classColumn: 'col-xl-2-otp p-1',
    maxlength: 1,
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
  new Otpbox({
    value: '',
    key: 'digit2',
    required: true,
    order: 2,
    type: 'text',
    maxlength: 1,
    classColumn: 'col-xl-2-otp p-1',
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
  new Otpbox({
    value: '',
    key: 'digit3',
    required: true,
    order: 3,
    type: 'text',
    maxlength: 1,
    classColumn: 'col-xl-2-otp p-1',
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
  new Otpbox({
    value: '',
    key: 'digit4',
    required: true,
    order: 4,
    type: 'text',
    maxlength: 1,
    classColumn: 'col-xl-2-otp p-1',
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
  new Otpbox({
    value: '',
    key: 'digit5',
    required: true,
    order: 5,
    type: 'text',
    classColumn: 'col-xl-2-otp p-1',
    maxlength: 1,
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
  new Otpbox({
    value: '',
    key: 'digit6',
    required: true,
    order: 6,
    type: 'text',
    classColumn: 'col-xl-2-otp p-1',
    maxlength: 1,
    validators: [Validators.required, Validators.pattern('[0-9]'), Validators.maxLength(1)],
  }),
];
